# The following manifests contain a self-signed issuer CR and a certificate CR.
# More document can be found at https://docs.cert-manager.io
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: {{ include "resource.default.name" . }}-webhook-service
  namespace: {{ include "resource.default.namespace" . }}
spec:
  dnsNames:
  - {{ include "resource.default.name" . }}.{{ include "resource.default.namespace" . }}.svc
  - {{ include "resource.default.name" . }}.{{ include "resource.default.namespace" . }}.svc.cluster.local
  issuerRef:
    kind: ClusterIssuer
    name: {{ .Values.managementCluster.clusterIssuer }}
  secretName: {{ include "resource.default.name" . }}-webhook-server-cert
