{{- if .Values.webhook.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: {{ include "resource.default.name" . }}-webhook
  namespace: {{ include "resource.default.namespace" . }}
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    {{- include "labels.selector" . | nindent 4 }}
{{- end }}
