apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: {{ include "resource.default.namespace" . }}/{{ include "resource.default.name" . }}-webhook-cert
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: {{ include "resource.default.name" . }}-validating-webhook
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "resource.default.name" . }}-webhook
      namespace: {{ .Release.Namespace }}
      path: /validate-alertmanager-config
      port: 443
  failurePolicy: Fail
  name: alertmanagerconfig.observability.giantswarm.io
  # Limit the validation only to the alertmanager-config secrets
  objectSelector:
    matchLabels:
      observability.giantswarm.io/kind: alertmanager-config
    matchExpressions:
      - key: observability.giantswarm.io/tenant
        operator: Exists
  rules:
    - apiGroups:
        - ""
      apiVersions:
        - v1
      operations:
        - CREATE
        - UPDATE
      resources:
        - secrets
  sideEffects: None
