
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: {{ include "resource.default.name"  . }}-validating-webhook
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "resource.default.name"  . }}-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /validate--v1-secret
      port: 443
  failurePolicy: Fail
  name: alertmanagerconfig.observability.giantswarm.io
  rules:
    - apiGroups:
        - ""
      apiVersions:
        - v1
      operations:
        - CREATE
        - UPDATE
      resources:
        - secrets
  sideEffects: None
