{{- if .Values.webhook.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: {{ include "resource.default.namespace" . }}/{{ include "resource.default.name" . }}-webhook-cert
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: {{ include "resource.default.name" . }}-validating-webhook
webhooks:
{{- if .Values.webhook.validatingWebhooks.alertmanagerConfig.enabled }}
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "resource.default.name" . }}-webhook
      namespace: {{ .Release.Namespace }}
      path: /validate-alertmanager-config
      port: 443
  failurePolicy: Fail
  name: alertmanagerconfig.observability.giantswarm.io
  objectSelector:
    matchLabels:
      observability.giantswarm.io/kind: alertmanager-config
    matchExpressions:
      - key: observability.giantswarm.io/tenant
        operator: Exists
  rules:
    - apiGroups:
        - ""
      apiVersions:
        - v1
      operations:
        - CREATE
        - UPDATE
      resources:
        - secrets
  sideEffects: None
{{- end }}
{{- if .Values.webhook.validatingWebhooks.grafanaOrganization.enabled }}
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "resource.default.name" . }}-webhook
      namespace: {{ .Release.Namespace }}
      path: /validate-v1alpha1-grafana-organization
      port: 443
  failurePolicy: Fail
  name: grafanaorganization.observability.giantswarm.io
  rules:
    - apiGroups:
        - observability.giantswarm.io
      apiVersions:
        - v1alpha1
      operations:
        - CREATE
        - UPDATE
      resources:
        - grafanaorganizations
  sideEffects: None
{{- end }}
{{- end }}
