apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: {{ include "alertmanager-secret.name" . }}
  namespace: {{ include "resource.default.namespace" . }}
data:
  {{- /* Template all .helm-template files found in files/alertmanager with values under alertmanager key */ -}}
  {{ range $path, $content :=  .Files.Glob  "files/alertmanager/*.helm-template" }}
    {{ base $path | trimSuffix ".helm-template" }}: {{ tpl (printf "%s" $content) $.Values | b64enc }}
  {{ end }}

  {{- /* Add all other non .helm-template files found in files/alertmanager */ -}}
  {{ range $path, $content :=  .Files.Glob  "files/alertmanager/*" }}
  {{ if not (hasSuffix ".helm-template" $path) }}
    {{ base $path }}: {{ (printf "%s" $content) | b64enc }}
  {{ end }}
  {{ end }}
type: Opaque
