# permissions for end users to view grafanaorganizations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: grafanaorganization-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: observability-operator
    app.kubernetes.io/part-of: observability-operator
    app.kubernetes.io/managed-by: kustomize
  name: grafanaorganization-viewer-role
rules:
- apiGroups:
  - observability.giantswarm.io
  resources:
  - grafanaorganizations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - observability.giantswarm.io
  resources:
  - grafanaorganizations/status
  verbs:
  - get
