# permissions for end users to view orgs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: org-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: observability-operator
    app.kubernetes.io/part-of: observability-operator
    app.kubernetes.io/managed-by: kustomize
  name: org-viewer-role
rules:
- apiGroups:
  - organization.giantswarm.io
  resources:
  - orgs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - organization.giantswarm.io
  resources:
  - orgs/status
  verbs:
  - get
