---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps/finalizers
  - secrets/finalizers
  verbs:
  - update
- apiGroups:
  - cluster.giantswarm.io
  resources:
  - clusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.giantswarm.io
  resources:
  - clusters/finalizers
  verbs:
  - update
- apiGroups:
  - cluster.giantswarm.io
  resources:
  - clusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - observability.giantswarm.io
  resources:
  - grafanaorganizations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - observability.giantswarm.io
  resources:
  - grafanaorganizations/finalizers
  verbs:
  - update
- apiGroups:
  - observability.giantswarm.io
  resources:
  - grafanaorganizations/status
  verbs:
  - get
  - patch
  - update
