---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - configmaps/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - objectstorage.giantswarm.io
  resources:
  - Clusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - objectstorage.giantswarm.io
  resources:
  - Clusters/finalizers
  verbs:
  - update
- apiGroups:
  - objectstorage.giantswarm.io
  resources:
  - Clusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - observability.giantswarm.io
  resources:
  - grafanaorganizations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - observability.giantswarm.io
  resources:
  - grafanaorganizations/finalizers
  verbs:
  - update
- apiGroups:
  - observability.giantswarm.io
  resources:
  - grafanaorganizations/status
  verbs:
  - get
  - patch
  - update
