apiVersion: observability.giantswarm.io/v1alpha1
kind: GrafanaOrganization
metadata:
  labels:
    app.kubernetes.io/name: observability-operator
    app.kubernetes.io/managed-by: kustomize
  name: grafanaorganization-sample
spec:
  displayName: Giant Swarm
  rbac:
    admins:
    - my-awesome-admins
    - other-admins
    editors:
    - my-awesome-editors
    - other-editors
    viewers:
    - my-awesome-viewers
    - other-viewers
  tenants:
  - myawesometenants
