apiVersion: observability.giantswarm.io/v1alpha1
kind: GrafanaOrganization
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: observability-operator
  name: grafanaorganization-sample
spec:
  displayName: Giant Swarm
  rbac:
    admins:
    - my-awesome-admins
    - other-admins
    editors:
    - my-awesome-editors
    - other-editors
    viewers:
    - my-awesome-viewers
    - other-viewers
  tenants:
  - giantswarm
status:
  orgID: 2
  dataSources:
  - name: "mimir"
    ID: 1
  - name: "loki"
    ID: 2
