{{- if .Values.validationJob.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "resource.default.name" . }}-resources-validation
  namespace: {{ .Release.Namespace }}
  labels:
     {{- include "labels.common" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      labels:
        {{- include "labels.common" . | nindent 12 }}
    spec:
      serviceAccountName: {{ include "resource.default.name" . }}
      restartPolicy: OnFailure 
      containers:
      - name: {{ include "resource.default.name" . }}-resources-validation
        image: "{{ .Values.validationJob.image.registry }}/{{ .Values.validationJob.image.name }}:{{ .Values.validationJob.image.tag }}"
        imagePullPolicy: {{ .Values.validationJob.image.pullPolicy }}
        args:
        - "-n={{ include "resource.default.name" . }}"
        - "get"
        - "pods"
        - "-l=app.kubernetes.io/name=observability-operator"
        - "--field-selector=status.phase=Running"
        securityContext:
          {{- with .Values.validationJob.containerSecurityContext }}
            {{- . | toYaml | nindent 10 }}
          {{- end }}
{{- end }}
