name: Alertmanager integration tests

on:
  pull_request:
    paths:
      - helm/observability-operator/files/alertmanager/**
jobs:
  test-alertmanager-integrations:
    name: Test Alertmanager integrations
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - run: make tests-alertmanager-integrations
