name: Alertmanager integration tests

on:
  pull_request:
    paths:
      - helm/observability-operator/files/alertmanager/**
jobs:
  test-alertmanager-integrations:
    name: Test Alertmanager integrations
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - run: make tests-alertmanager-integrations
