name: Alertmanager integration tests

on:
  pull_request:
    paths:
      - helm/observability-operator/files/alertmanager/**
jobs:
  test-alertmanager-integrations:
    name: Test Alertmanager integrations
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - run: make tests-alertmanager-integrations
