name: Alertmanager checks

on: pull_request

jobs:
  validate-alertmanager:
    name: Check Alertmanager Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Run alertmanager version sync check
        run: ./hack/bin/check-alertmanager-version.sh
  test-alertmanager-routes:
    name: Test Alertmanager routes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - run: make tests-alertmanager-routes
